version: '3.8'

services:
  creator-ai:
    build: .
    ports:
      - "3000:3000"  # API server
      - "8080:8080"  # WebSocket server
    volumes:
      - ./models:/app/models           # Persistent model storage
      - ./output:/app/output           # Generated content output
      - ./uploads:/app/uploads         # Training data uploads
      - ./data:/app/data               # Persistent data
    environment:
      - NODE_ENV=production
      - API_PORT=3000
      - WS_PORT=8080
      - MAX_MEMORY=4GB
      - GPU_ACCELERATION=auto
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates if needed
    depends_on:
      - creator-ai
    restart: unless-stopped

volumes:
  models:
    driver: local
  output:
    driver: local
  uploads:
    driver: local
  data:
    driver: local

networks:
  default:
    driver: bridge