apiVersion: apps/v1
kind: Deployment
metadata:
  name: creator-ai-api
  labels:
    app: creator-ai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creator-ai-api
  template:
    metadata:
      labels:
        app: creator-ai-api
    spec:
      containers:
      - name: creator-ai-api
        image: creator-ai:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        volumeMounts:
        - name: models-storage
          mountPath: /app/models
        - name: data-storage
          mountPath: /app/training_data
        - name: output-storage
          mountPath: /app/output
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: creator-ai-models-pvc
      - name: data-storage
        persistentVolumeClaim:
          claimName: creator-ai-data-pvc
      - name: output-storage
        persistentVolumeClaim:
          claimName: creator-ai-output-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: creator-ai-api-service
spec:
  selector:
    app: creator-ai-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creator-ai-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creator-ai-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creator-ai-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: creator-ai-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  TFJS_BACKEND: "cpu"

---
apiVersion: v1
kind: Secret
metadata:
  name: creator-ai-secrets
type: Opaque
data:
  session-secret: <base64-encoded-secret>
  
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: creator-ai-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creator-ai-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creator-ai-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.creator-ai.your-domain.com
    secretName: creator-ai-tls
  rules:
  - host: api.creator-ai.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: creator-ai-api-service
            port:
              number: 80